//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Cancellations = new HashSet<Cancellation>();
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int BookingID { get; set; }
        public int FlightID { get; set; }
        public string Email { get; set; }
        public int ClassID { get; set; }
        public int SeatID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int NoofTickets { get; set; }
        public int BookingAmount { get; set; }
        public System.DateTime DateOfDeparture { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool ReturnTicket { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Seat Seat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
    }
}
