//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int CancellationID { get; set; }
        public System.DateTime CancellationDate { get; set; }
        public int FlightID { get; set; }
        public int RefundAmount { get; set; }
        public int BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
